services:
  database:
    image: mariadb:lts
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: asd345#$%
    volumes:
      - ./db/mariadb.cnf:/etc/mysql/mariadb.cnf:ro
      - /var/lib/mysql:/var/lib/mysql:Z

  queue:
    image: rabbitmq:4-management-alpine
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:5672:5672
      - 127.0.0.1:8080:8080
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ADMIN_PASS
    volumes:
      - ./queue/00-listeners.conf:/etc/rabbitmq/conf.d/00-listeners.conf

  cache:
    image: memcached:1-alpine
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:11211:11211

  registry:
    image: registry:2
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:5000:5000

  dns:
    image: ubuntu/bind9:9.18-22.04_beta
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:53:53
      - 0.0.0.0:53:53/udp
    environment:
      - TZ=UTC
    volumes:
      - ./dns/named.conf.options:/etc/bind/named.conf.options:ro
      - ./dns/named.conf.local:/etc/bind/named.conf.local:ro
      - ./dns/zones/db.dns.computer:/etc/bind/db.dns.computer:ro
      - ./dns/zones/db.registry.computer:/etc/bind/db.registry.computer:ro
      - ./dns/zones/db.database.computer:/etc/bind/db.database.computer:ro
      - ./dns/zones/db.database.computer:/etc/bind/db.control.computer:ro

