services:
  database:
    image: mariadb:lts
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: asd345#$%
    volumes:
      - ./db/mariadb.cnf:/etc/mysql/mariadb.cnf:ro

  registry:
    image: registry:2
    restart: always
    ports:
      - 0.0.0.0:5000:5000

  dns:
    image: ubuntu/bind9:9.18-22.04_beta
    restart: always
    ports:
      - 0.0.0.0:53:53
      - 0.0.0.0:53:53/udp
    environment:
      - TZ=UTC
    volumes:
      - ./dns/named.conf.options:/etc/bind/named.conf.options:ro
      - ./dns/named.conf.local:/etc/bind/named.conf.local:ro
      - ./dns/zones/db.dns.computer:/etc/bind/db.dns.computer:ro
      - ./dns/zones/db.registry.computer:/etc/bind/db.registry.computer:ro
      - ./dns/zones/db.database.computer:/etc/bind/db.database.computer:ro
      - ./dns/zones/db.database.computer:/etc/bind/db.control.computer:ro

  keystone:
    depends_on: 
      - dns
    build: ./openstack/keystone
    ports:
      - 0.0.0.0:5555:5555
    volumes:
      - ./openstack/keystone/keystone.conf:/etc/keystone/keystone.conf:ro
