- name: "Run 'horizon' service"
  community.docker.docker_compose_v2:
    recreate: always
    services: 
      - horizon
    project_src: /super
    files:
      - openstack.compose.yml
  become: true
