services:
  keystone:
    build: ./openstack/keystone
    network_mode: host
    ports:
      - 0.0.0.0:5555:5555
    volumes:
      - ./openstack/keystone/apache.ports.conf:/etc/apache2/ports.conf:ro
      - ./openstack/keystone/keystone.conf:/etc/keystone/keystone.conf:ro

  glance:
    depends_on: 
      - keystone
    build: ./openstack/glance
    network_mode: host
    ports:
      - 0.0.0.0:9292:9292
    volumes:
      - ./openstack/keystone/apache.ports.conf:/etc/apache2/ports.conf:ro
      - ./openstack/glance/glance-api.conf:/etc/glance/glance-api.conf
