cidr_networks:
  bmaas:     10.88.104.0/24        # for containers on the bmaas network

used_ips:
  # bmaas ips
  - "10.88.104.0,10.88.104.10"     # reserve for routers or other infrastructure
  - "10.88.104.30,10.88.104.255"   # reserve for ironic IPMI and provisioning

provider_networks:
  # Network definition to connect Ironic LXC containers to the bmaas network
  # on the infra hosts
  - network:
      net_name: physnet_neutron
      container_type: "veth"
      container_bridge: "br-bmaas"
      container_interface: "eth15"
      ip_from_q: bmaas
      type: "vlan"
      range: "3003:3003"
      group_binds:
        - ironic_api_container
        - ironic_compute_container
        - ironic_inspector_container


# ironic API and conductor
ironic-infra_hosts:
  infra1: *_infra1_
  infra2: *_infra2_
  infra3: *_infra3_
  infra4: *_infra4_

# nova used by ironic for machine state management
ironic-compute_hosts:
  infra1: *_infra1_
  infra2: *_infra2_
  infra3: *_infra3_
  infra4: *_infra4_

# Ironic-inspector can only support a single instance at the moment
# High availability for ironic-inspector is not yet implemented
ironic-inspector_hosts:
  infra1: *_infra1_
